extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "next"
  - "prettier"
plugins:
  - "react"
  - "@typescript-eslint"
rules:
  "react/react-in-jsx-scope": "off"
