name: build
on:
  - pull_request
env:
  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "corepack enable"
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - run: yarn install
      - run: yarn run export
